name: flutter_format

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  surveyor:
    git:
      url: https://github.com/pq/surveyor.git
      ref: master

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
